%% regcorr
% Performs regression correction by wavelengths.
%
%% Description
% |[data_out, R] = regcorr(data_in, info, hem)| takes a light-level array
% |data_in| of the format MEAS x TIME, and using the scan metadata in
% |info.pairs| and a WL x MEAS |hem| array generated by |gethem|, performs
% a regression correction for each wavelength of the data, which is
% returned in the MEAS x TIME array |data_out|. The corresponding
% correlation coefficients for each measurement are returned in |R| as a
% MEAS x 1 array.
%
% The formal equation for the regression is:
% 
%   x_hat = x - h * hp * x;
% 
% where |x| is the transpose (TIME x MEAS) of the original data for a
% single wavelength, |h| is the |hem| transpose (TIME x 1) for a single
% wavelength, |hp| is the pseudoinverse (1 x TIME) of |h|, and |x_hat| is the
% estimation of the true |x|.
%
%% See Also
% <gethem_help.html gethem> | <detrend_tts_help.html detrend_tts>